apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  schedule: "0 0 1 * *"
  startingDeadlineSeconds: 300  # 5 минут
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          containers:
          - name: django
            image: django_app
            imagePullPolicy: IfNotPresent
            command: ["python3", "manage.py", "clearsessions"]
            envFrom:
            - secretRef:
                name: django-secrets
          restartPolicy: Never