apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: django_app
        imagePullPolicy: IfNotPresent
        command: ["python3", "manage.py", "migrate"]
        envFrom:
        - secretRef:
            name: django-secrets
      restartPolicy: Never